package web

import (
	"crypto/rand"
	"encoding/hex"
	"sort"
	"sync"
	"time"

	"github.com/mahdi-salmanzade/hippo"
)

// defaultRecentCap is how many completed calls State keeps. The UI's
// recent-calls table polls this ring on a 3s timer; 100 rows is plenty
// for a playground and cheap in memory (~20KB worst-case).
const defaultRecentCap = 100

// State is the in-process bookkeeping for the web server: completed
// calls for the recent-calls ring, aggregated spend by provider/task,
// plus a session map for streaming chat turns. It is kept outside the
// hippo.Brain by design - Brain stays ignorant of the UI so the library
// core remains reusable without pulling the web package in.
type State struct {
	mu       sync.RWMutex
	recent   []CallRecord
	cap      int
	sessions map[string]*ChatSession
}

// CallRecord is one line of the recent-calls table. Prompt/Response are
// truncated in Record (see truncatePreview) so the ring stays cheap to
// walk and render.
//
// ID correlates a placeholder insert at stream-start with its eventual
// update at usage-arrival, so the hippo_spend tool fired mid-stream
// can see the in-flight turn instead of reporting it as "not yet
// happened". Generated by Record when empty.
type CallRecord struct {
	ID        string
	Timestamp time.Time
	Provider  string
	Model     string
	Task      string
	Prompt    string
	Response  string
	Usage     hippo.Usage
	CostUSD   float64
	LatencyMS int64
	ToolCalls int
	Error     string
	// Pending signals that this record was inserted optimistically at
	// stream-start and hasn't yet been updated with real usage/cost.
	// The Spend page and tool can de-emphasise it.
	Pending bool
}

// NewState builds a State with the default capacity.
func NewState() *State {
	return &State{
		cap:      defaultRecentCap,
		sessions: make(map[string]*ChatSession),
	}
}

// Record appends one CallRecord to the ring, evicting the oldest entry
// once cap is reached. If r.ID is empty, a fresh id is generated and
// stored on the inserted record — the returned string is that id so
// callers can Update it later.
func (s *State) Record(r CallRecord) string {
	r.Prompt = truncatePreview(r.Prompt)
	r.Response = truncatePreview(r.Response)
	if r.ID == "" {
		r.ID = newRecordID()
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if len(s.recent) >= s.cap {
		// Drop the oldest (index 0). Cheap for cap=100; a real
		// ring would be nicer but for 100 rows the copy doesn't
		// measurably cost.
		copy(s.recent, s.recent[1:])
		s.recent = s.recent[:len(s.recent)-1]
	}
	s.recent = append(s.recent, r)
	return r.ID
}

// UpdateByID finds a previously-recorded call by id and applies fn to
// it. Used to patch a pending placeholder with final usage and cost
// once the stream delivers a usage event. Returns true if the record
// was found and updated; false if it was evicted from the ring first.
func (s *State) UpdateByID(id string, fn func(r *CallRecord)) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	for i := range s.recent {
		if s.recent[i].ID == id {
			fn(&s.recent[i])
			// Re-truncate in case content grew in the update.
			s.recent[i].Prompt = truncatePreview(s.recent[i].Prompt)
			s.recent[i].Response = truncatePreview(s.recent[i].Response)
			return true
		}
	}
	return false
}

// RemoveByID drops a record from the ring. Used when a stream was
// cancelled before it produced usage data — the placeholder shouldn't
// stick around as a half-row in the Recent Calls table. Returns true
// when a record was removed.
func (s *State) RemoveByID(id string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	for i := range s.recent {
		if s.recent[i].ID == id {
			s.recent = append(s.recent[:i], s.recent[i+1:]...)
			return true
		}
	}
	return false
}

// newRecordID returns a compact random id for in-flight tracking. Not
// cryptographic — collision-resistance over a 100-element ring is all
// we need.
func newRecordID() string {
	var b [6]byte
	_, _ = rand.Read(b[:])
	return hex.EncodeToString(b[:])
}

// Recent returns up to n completed records, newest first. Pending
// (in-flight) placeholders are hidden from the UI table — they have
// no provider/model/cost yet and would render as empty rows.
func (s *State) Recent(n int) []CallRecord {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]CallRecord, 0, len(s.recent))
	for i := len(s.recent) - 1; i >= 0; i-- {
		if s.recent[i].Pending {
			continue
		}
		out = append(out, s.recent[i])
		if n > 0 && len(out) >= n {
			break
		}
	}
	return out
}

// TotalSpend sums CostUSD across all recorded calls.
func (s *State) TotalSpend() float64 {
	s.mu.RLock()
	defer s.mu.RUnlock()
	var total float64
	for _, r := range s.recent {
		total += r.CostUSD
	}
	return total
}

// SpendByProvider returns a provider → USD total. Providers absent from
// the ring are omitted. Order is provider-name ascending.
func (s *State) SpendByProvider() []ProviderSpend {
	s.mu.RLock()
	defer s.mu.RUnlock()
	m := map[string]float64{}
	for _, r := range s.recent {
		if r.Provider == "" {
			continue
		}
		m[r.Provider] += r.CostUSD
	}
	out := make([]ProviderSpend, 0, len(m))
	for k, v := range m {
		out = append(out, ProviderSpend{Provider: k, USD: v})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Provider < out[j].Provider })
	return out
}

// SpendByTask returns a task → USD total.
func (s *State) SpendByTask() []TaskSpend {
	s.mu.RLock()
	defer s.mu.RUnlock()
	m := map[string]float64{}
	for _, r := range s.recent {
		key := r.Task
		if key == "" {
			key = "(none)"
		}
		m[key] += r.CostUSD
	}
	out := make([]TaskSpend, 0, len(m))
	for k, v := range m {
		out = append(out, TaskSpend{Task: k, USD: v})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Task < out[j].Task })
	return out
}

// SpendByModel returns a model → USD total. Empty model ids are
// bucketed as "(unknown)". Order is model-name ascending.
func (s *State) SpendByModel() []ModelSpend {
	s.mu.RLock()
	defer s.mu.RUnlock()
	m := map[string]float64{}
	for _, r := range s.recent {
		key := r.Model
		if key == "" {
			key = "(unknown)"
		}
		m[key] += r.CostUSD
	}
	out := make([]ModelSpend, 0, len(m))
	for k, v := range m {
		out = append(out, ModelSpend{Model: k, USD: v})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].USD > out[j].USD })
	return out
}

// CallCount returns the number of rows currently in the ring, pending
// placeholders included. Use CompletedCount when only finished turns
// matter (e.g. the chat tool splits them explicitly).
func (s *State) CallCount() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.recent)
}

// CompletedCount counts only non-pending records.
func (s *State) CompletedCount() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	n := 0
	for i := range s.recent {
		if !s.recent[i].Pending {
			n++
		}
	}
	return n
}

// PendingCount counts placeholders that haven't received a usage
// event yet — always ≤ 1 under normal single-user operation, but the
// tool surfaces it so the model can explain the in-flight state.
func (s *State) PendingCount() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	n := 0
	for i := range s.recent {
		if s.recent[i].Pending {
			n++
		}
	}
	return n
}

// ProviderSpend is one row of SpendByProvider.
type ProviderSpend struct {
	Provider string
	USD      float64
}

// TaskSpend is one row of SpendByTask.
type TaskSpend struct {
	Task string
	USD  float64
}

// ModelSpend is one row of SpendByModel.
type ModelSpend struct {
	Model string
	USD   float64
}

// ChatSession is an in-flight chat turn: its parameters were POSTed via
// /chat and the SSE stream at /chat/stream will consume them. Sessions
// self-destruct on first stream attachment or after sessionTTL.
type ChatSession struct {
	ID        string
	Call      hippo.Call
	CreatedAt time.Time
	Consumed  bool
	// ChatID is the persistent chat drawer id this turn belongs to
	// (see ChatStore). Empty means the client opted out of
	// persistence; the server then won't try to Append the turns.
	ChatID string
}

// sessionTTL is the maximum time a session can sit unclaimed between
// POST /chat and GET /chat/stream.
const sessionTTL = 5 * time.Minute

// PutSession stores a chat session keyed by id.
func (s *State) PutSession(id string, sess *ChatSession) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.pruneSessionsLocked()
	s.sessions[id] = sess
}

// TakeSession retrieves and removes a session by id. Returns nil if the
// session is unknown or already consumed.
func (s *State) TakeSession(id string) *ChatSession {
	s.mu.Lock()
	defer s.mu.Unlock()
	sess, ok := s.sessions[id]
	if !ok || sess.Consumed {
		return nil
	}
	sess.Consumed = true
	delete(s.sessions, id)
	return sess
}

func (s *State) pruneSessionsLocked() {
	cutoff := time.Now().Add(-sessionTTL)
	for id, sess := range s.sessions {
		if sess.CreatedAt.Before(cutoff) {
			delete(s.sessions, id)
		}
	}
}

// truncatePreview trims a string to its first 200 characters, suffixing
// "…" when the original was longer. Called on both Prompt and Response
// before they enter the ring so the table stays light.
func truncatePreview(s string) string {
	const max = 200
	if len(s) <= max {
		return s
	}
	return s[:max] + "…"
}
